/**
 * 
 */
package eclipsemate.bundle.model;

public enum OUTPUT_TYPE {
	DISCARD
	,REPLACE_SELECTION
	,REPLACE_SELECTED_LINES
	,REPLACE_LINE
	,REPLACE_WORD
	,REPLACE_DOCUMENT
	,INSERT_AS_TEXT
	,INSERT_AS_SNIPPET
	//,INSERT_AS_TEMPLATE
	,SHOW_AS_HTML
	,SHOW_AS_TOOLTIP
	,CREATE_NEW_DOCUMENT
	,OUTPUT_TO_CONSOLE
	,
}